name: Deploy Project
# Events : https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#pull_request
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install Node js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '24'
      - name: Install Dependencies
        run: npm ci
      - name: Run test
        run: |
          npm test
  deploy:
    needs: test #This add dependency and runs the jobs sequentially
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install Node js
        uses: actions/setup-node@v5.0.0
        with:
          node-version: '24'
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying...."  
    