name: Events Demo
#event filter and activity types
#events
# https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#filter-pattern-cheat-sheet
on: 
  pull_request:
    types:
     - opened
    branches:
      - main
      - feature/*  # feature/new , feature/new/01
      - dev-*
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*  # feature/new , feature/new/01
      - dev-*
    paths-ignore:
      - '.github/workflows/*' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run : echo "${{ toJSON(github.event) }}"
      - name: Get Code
        uses: actions/checkout@v5
      - name: Install Dependencies 
        run: npm ci
      - name: Test Code
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deployment
        run: echo "Running deployment"
