name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    # Github Provides lot of runners docs.github.com
    runs-on: ubuntu_latest
    steps:
      - name: Print greeting
        run: eco "Hello !!"
      - name: Print goodbye
        run: eco "Byee !!"
        
    
